name: Build-Test-Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:        
      - uses: actions/checkout@v4   
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/
      - name: Run Automated Tests
        run: |
          echo "Running automated tests..."

  release:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
    
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/
      - name: Check dist files
        run: |
          echo "Checking files in dist/"
          ls -al dist/
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ Tests passed. Releasing new dev build..."
          gh release create "dev-$(date +%s)" dist/* --notes "Automated release after successful tests"
